# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(1080, 720)
        MplMainWindow.setAutoFillBackground(False)
        MplMainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.mplcentralwidget = QtWidgets.QWidget(MplMainWindow)
        self.mplcentralwidget.setObjectName("mplcentralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mplcentralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.mplcentralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mpl = MplWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.verticalLayout_5.addWidget(self.mpl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pauseButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.pauseButton.setFont(font)
        self.pauseButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_2.addWidget(self.pauseButton)
        self.stepModeButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepModeButton.sizePolicy().hasHeightForWidth())
        self.stepModeButton.setSizePolicy(sizePolicy)
        self.stepModeButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.stepModeButton.setFont(font)
        self.stepModeButton.setObjectName("stepModeButton")
        self.horizontalLayout_2.addWidget(self.stepModeButton)
        self.nextStepButton = QtWidgets.QPushButton(self.tab_3)
        self.nextStepButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextStepButton.sizePolicy().hasHeightForWidth())
        self.nextStepButton.setSizePolicy(sizePolicy)
        self.nextStepButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.nextStepButton.setFont(font)
        self.nextStepButton.setObjectName("nextStepButton")
        self.horizontalLayout_2.addWidget(self.nextStepButton)
        self.resumeButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resumeButton.sizePolicy().hasHeightForWidth())
        self.resumeButton.setSizePolicy(sizePolicy)
        self.resumeButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.resumeButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("play")
        self.resumeButton.setIcon(icon)
        self.resumeButton.setObjectName("resumeButton")
        self.horizontalLayout_2.addWidget(self.resumeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimum(50)
        self.horizontalSlider.setMaximum(1500)
        self.horizontalSlider.setSingleStep(100)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(True)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_5.addWidget(self.horizontalSlider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.genLabel = QtWidgets.QLabel(self.tab_3)
        self.genLabel.setObjectName("genLabel")
        self.verticalLayout_2.addWidget(self.genLabel)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.speedLabel = QtWidgets.QLabel(self.tab_3)
        self.speedLabel.setObjectName("speedLabel")
        self.verticalLayout_2.addWidget(self.speedLabel)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.fileLabel = QtWidgets.QLabel(self.tab_3)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout_2.addWidget(self.fileLabel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.genMod = QtWidgets.QLabel(self.tab_3)
        self.genMod.setObjectName("genMod")
        self.verticalLayout.addWidget(self.genMod)
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.speedMod = QtWidgets.QLabel(self.tab_3)
        self.speedMod.setObjectName("speedMod")
        self.verticalLayout.addWidget(self.speedMod)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.fileMod = QtWidgets.QLabel(self.tab_3)
        self.fileMod.setObjectName("fileMod")
        self.verticalLayout.addWidget(self.fileMod)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setObjectName("listView")
        self.verticalLayout_6.addWidget(self.listView)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.commandLinkButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("a")
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_4.addWidget(self.commandLinkButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.menubar = QtWidgets.QMenuBar(MplMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        MplMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MplMainWindow)
        self.statusbar.setObjectName("statusbar")
        MplMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MplMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "MainWindow"))
        self.pauseButton.setText(_translate("MplMainWindow", " Pause Simulation"))
        self.stepModeButton.setText(_translate("MplMainWindow", "Enable Step-by-Step"))
        self.nextStepButton.setText(_translate("MplMainWindow", "Next Step"))
        self.resumeButton.setText(_translate("MplMainWindow", "Save Configuration"))
        self.label.setText(_translate("MplMainWindow", "Simulation Speed"))
        self.genLabel.setText(_translate("MplMainWindow", "Number of generations:"))
        self.speedLabel.setText(_translate("MplMainWindow", "Generation interval (ms):"))
        self.fileLabel.setText(_translate("MplMainWindow", "Current configuration:"))
        self.genMod.setText(_translate("MplMainWindow", "0"))
        self.speedMod.setText(_translate("MplMainWindow", "0"))
        self.fileMod.setText(_translate("MplMainWindow", "0"))
        self.commandLinkButton.setText(_translate("MplMainWindow", "Use selected configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MplMainWindow", "Simulation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MplMainWindow", "Make a configuration"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MplMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MplMainWindow()
    ui.setupUi(MplMainWindow)
    MplMainWindow.show()
    sys.exit(app.exec_())

